### ISSUE TITLE
https://www.youtube.com/watch?v=JLx8_BceN1k

### ISSUE THREAD

**Issue by kritohanzo** [AllowDeny0123/archlinux-vnc#2]
https://www.youtube.com/watch?v=JLx8_BceN1k

_Originally posted by @AllowDeny0123 in https://github.com/AllowDeny0123/archlinux-vnc/issues/1#issuecomment-2248697020_
            
author very bad guy, ONLY DIRTY CHAT

**Comment by kritohanzo** [comment]
FIX BUG AUTHOR

**Comment by AllowDeny0123** [comment]
![understandable](https://cdn.arstechnica.net/wp-content/uploads/2012/06/torvaldsnvidia-640x424.jpg)
